name: web_translator_ml
description: Flutter Web App to translate Mapudungun to English and Spanish
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  freezed: ^2.1.0+1
  get_it: ^7.2.0
  hive: ^2.2.3
  injectable: ^2.1.0
  intl: ^0.17.0
  side_sheet: ^1.0.3
  speech_to_text: ^6.1.1
  talker: ^2.1.0+1
  rflutter_alert: ^2.0.4
  flutter_tts: ^3.6.2
  modal_bottom_sheet: ^2.1.2
  assets_audio_player: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  #Injectable code generators
  injectable_generator: null
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
